# Generated by Django 4.1.3 on 2022-11-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
