# Generated by Django 4.1.3 on 2022-11-21 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='Наименование')),
                ('description', models.TextField(max_length=1500, null=True, verbose_name='Описание')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('weight', models.IntegerField(null=True, verbose_name='Вес')),
                ('protein', models.IntegerField(help_text='на 100 грамм', null=True, verbose_name='Белки')),
                ('carbs', models.IntegerField(help_text='на 100 грамм', null=True, verbose_name='Углеводы')),
                ('fats', models.IntegerField(help_text='на 100 грамм', null=True, verbose_name='Жиры')),
                ('ingredients', models.TextField(null=True, verbose_name='Ингридиенты')),
                ('status', models.CharField(choices=[('g', 'generic'), ('d', 'discount')], default='g', max_length=1, verbose_name='Статус')),
                ('expiration_period', models.IntegerField(null=True, verbose_name='Срок годности')),
                ('creation_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('update_date', models.DateField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_categories.category', verbose_name='Категория')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_categories.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
