# Generated by Django 4.1.3 on 2022-11-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0002_rename_product_good_goodssold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodssold',
            name='sold',
            field=models.IntegerField(default=0, verbose_name='Продано'),
        ),
    ]
