# Generated by Django 4.1.3 on 2022-11-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_market', '0003_alter_goodssold_sold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodssold',
            options={'verbose_name': 'Продано товара', 'verbose_name_plural': 'Продано товаров'},
        ),
    ]
